# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solutionPath: CarStore

jobs:
- job: build_linux
  # pool section defines what agent the job will run on
  pool:
    # get a microsoft-hosted agent running the latest ubuntu linux.
    vmImage: 'ubuntu-latest'

steps:
- task: SonarCloudPrepare@1
  displayName: sonarcloud prepare analysis
  inputs:
    SonarCloud: 'sonarcloud-kirtipatel98'
    organization: '2006-jun15-net'
    scannerMode: 'MSBuild'
    projectKey: '2006-jun15-net_kirti-project1'
    projectName: 'Kirti project1 Car Store'

- script: dotnet build -c Release
  displayName: dotnet build
  workingDirectory: $(solutionPath)

- task: SonarCloudAnalyze@1
  displayName: sonarcloud prepare analysis

- task: SonarCloudPublish@1
  displayName: sonarcloud prepare analysis
  inputs:
    pollingTimeoutSec: '300'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/*/coverage.cobertura.xml'
    failIfCoverageEmpty: true

- script: dotnet build -c Release -o ../publish
  displayName: dotnet build
  workingDirectory: $(solutionPath)

- task: AzureRmWebAppDeployment@4
  displayName: azure app service deploy
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(a8f0024b-b40d-44a8-8a01-2d63b02fb4c7)'
    appType: 'webApp'
    WebAppName: '2006-project1'
    # deployToSlotOrASE: true
    # ResourceGroupName: '2006-training-rg'
    # SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/publish'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
